global:
  resolve_timeout: 5m
  smtp_smarthost: "smtp.gmail.com:587"
  smtp_from: "${EMAIL_USER}"
  smtp_auth_username: "${EMAIL_USER}"
  smtp_auth_password: "${EMAIL_PASSWORD}"
  smtp_require_tls: true

route:
  group_by: ["alertname", "job"]
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 4h
  receiver: "email-notifications"

receivers:
  - name: "email-notifications"
    email_configs:
      - to: "${EMAIL_USER}"
        send_resolved: true
